### ISSUE TITLE
Need stronger LDO

### ISSUE THREAD

**Issue by glynhudson** [openenergymonitor/HeatpumpMonitor#3]
Using the MCP1702 as the LDO is problematic. The ESP can current spike up to [300mA](http://blog.hekkers.net/tag/esp-12/). The spikes are quite narrow, so are mostly supplied by the reservoir/decoupling caps after the LDO.  There is a limit to how fat you can make these though without driving the LDO out of its stable region (22uF is the max in the spec).  The risk is the LDO runs into its current limit mode and folds the output voltage towards ground to protect itself. The symptoms will be frequent global resets since the ATMega will pick up on the supply rail flicker, generating a POR.

Check the waveforms at JP1 - the heavier load on the positive half cycle might well be taking the wall wart into saturation, upsetting that finely-tuned simultaneous power&sample section.

**Comment by TrystanLea** [comment]
Fixed in v3/v4
